version: 2
builds:
  - main: ./main.go
    ldflags:
      - -s -w -X github.com/bakito/argocd-touch-extension/version.Version={{.Version}}
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    hooks:
      post:
        # don't upx windows binaries as they make trouble with virus scanners
        - bash -c 'if [[ "{{ .Path }}" != *.exe ]] && [[ "{{ .Path }}" != *darwin* ]] && [[ "{{ .Path }}" != *openbsd* ]]; then upx {{ .Path }}; fi'

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
