apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "argocd-touch-extension.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-touch-extension.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- if not .Values.config }}{{ fail "config must not be empty" }}{{ end }}{{- .Values.config | toYaml | nindent 4 }}
