{{- if .Values.extensions.touch.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-extension-touch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: argocd-extension-touch
    app.kubernetes.io/instance: {{ .Release.Name }}
    {{- (index .Values "argo-cd").global.podLabels | toYaml | nindent 4 }}
  annotations:
    {{- (index .Values "argo-cd").global.podAnnotations | toYaml | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-extension-touch
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: argocd-extension-touch
        app.kubernetes.io/instance: {{ .Release.Name }}
        {{- (index .Values "argo-cd").global.podLabels | toYaml | nindent 8 }}
      annotations:
        {{- (index .Values "argo-cd").global.podAnnotations | toYaml | nindent 8 }}
    spec:
      serviceAccountName: argocd-server
      volumes:
        - name: config
          configMap:
            name: argocd-extension-touch
      containers:
        - name: extension-touch
          image: {{ .Values.extensions.touch.image.name }}:{{ .Values.extensions.touch.image.tag }}
          args:
            - '--config'
            - /config/config.yaml
            - '--service-address'
            - 'http://argocd-extension-touch:8080'
            - '--debug'
          ports:
            - name: api
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
          livenessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: api
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 100m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
{{- end }}