apiVersion: v1
kind: Service
metadata:
  name: {{ include "argocd-touch-extension.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "argocd-touch-extension.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: api
      protocol: TCP
      name: api
  selector:
    app.kubernetes.io/name: {{ include "argocd-touch-extension.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
