name: Upload Helm Chart

on:
  release:
    types:
      - published

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to ghcr.io
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build chart
        run: |
          VERSION=$(echo "${{github.event.release.tag_name }}" | sed 's/v//g')
          sed -i "s/^version:.*$/version: ${VERSION}/"        ./helm/Chart.yaml
          sed -i "s/^appVersion:.*$/appVersion: v${VERSION}/" ./helm/Chart.yaml
          make helm-docs
          helm package ./helm/ --version $VERSION --app-version v$VERSION -d dist
          helm push dist/argocd-touch-extension-${VERSION}.tgz oci://ghcr.io/bakito/helm-charts
